print("           TOKO ELEKTRONIK ALVIN NUSANTARA           ")
print("           =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=           ")
Nama_pembeli = input("Masukan nama pembeli : ")
Kode_barang  = input("Masukan kode barang  : ")
Harga        = int(input("Masukan harga    : "))
Jumlah_beli  = input("Masukan jumlah beli  : ")
print("           =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=           ")
print("Nama pembeli = ", Nama_pembeli)
print("Kode barang  = ", Kode_barang)
print("Harga        = ", Harga)
print("Jumlah beli  = ", Jumlah_beli)
print("Total harga  = ", int(Harga) * int(Jumlah_beli))