# penugasan pertama
a = 5
print('a = 10 -> ', a)
a += 3
print('a += 5 -> ', a)
a -= 9
print('a -= 3 -> ', a)
a *= 4
print('a *= 6 -> ', a)
a /= 16
print('a /= 8 -> ', a)
# penugasan kedua
a = int(a)
a %= 12
print('a %= 9 -> ', a)
a //= 34
print('a //= 6 -> ', a)
a **= 15
print('a **= 1 -> ', a)
a &= 21
print('a &= 2 -> ', a)
a |= 32
print('a |= 3 -> ', a)
a ^= 43
print('a ^= 4 -> ', a)
a >>= 22
print('a >>= 4 -> ', a)
a <<= 10
print('a <<= 4 -> ', a)